using System;
using EnumBugReproducer.Models.DAL;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EfCoreNpgsqlPublicEnumReproducer.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
		// this is the unchanged (except for this comment) migration generated by ef core
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "myschema");

            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:Enum:my_enum", "value_one,value2");

            migrationBuilder.CreateTable(
                name: "entities",
                schema: "myschema",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    my_discriminator = table.Column<MyEnum>(type: "my_enum", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_entities", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "entities",
                schema: "myschema");
        }
    }
}
